services:
    php:
        build: .
        restart: always
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - .:/app
        environment:
            - SERVER_NAME=:80
            - DATABASE_URL=mysql://root:root@db:3306/db_symfony?serverVersion=8.0.32
        depends_on:
            db:
                condition: service_healthy

    db:
        image: mariadb:10.11
        environment:
            MARIADB_ROOT_PASSWORD: root
            MARIADB_DATABASE: db_symfony
        ports:
            - "3307:3306"
        healthcheck:
            test: [ "CMD", "healthcheck.sh", "--connect", "--innodb_initialized" ]
            interval: 5s
            timeout: 5s
            retries: 5

    phpmyadmin:
        image: phpmyadmin:latest
        ports:
            - "8080:80"
        environment:
            - PMA_HOST=db

